# Generated by Django 2.0.4 on 2018-04-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_num', models.CharField(max_length=10)),
                ('flag_num', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_num', models.CharField(max_length=10)),
                ('flag_num', models.CharField(max_length=50)),
                ('last', models.DateTimeField(auto_now_add=True)),
                ('result', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_num', models.CharField(max_length=10)),
                ('fraction', models.IntegerField()),
                ('last', models.DateTimeField(auto_now=True)),
                ('flag_num', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_num', models.CharField(max_length=10)),
                ('player_num', models.CharField(max_length=10)),
                ('run', models.IntegerField()),
            ],
        ),
    ]
