# Generated by Django 2.1 on 2018-09-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_num', models.CharField(max_length=10)),
                ('flag_num', models.CharField(max_length=50)),
                ('last', models.DateTimeField(auto_now_add=True)),
                ('result', models.IntegerField()),
            ],
        ),
    ]
