# Generated by Django 2.1 on 2018-09-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_logs1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs1',
        ),
    ]
